### ISSUE TITLE
[issue] Saves Blank site as well

### ISSUE THREAD

**Issue by kavilrawat** [iammohan01/SlashSpaceGo#28]
Saves empty pages as well, and also allows to save it multiple times. 
<img width="1728" alt="image" src="https://github.com/iammohan01/SlashSpaceGo/assets/102759792/a2bdc106-65f2-4e27-815c-4ebd51f3c75a">

**Comment by iammohan01** [comment]
sure , will fix this

**Comment by iammohan01** [comment]
Fixed and merged
